### ISSUE TITLE
Unexpected behaviors in React JS

### ISSUE THREAD

**Issue by Rohith-JN** [cong-min/TagCloud#16]
I installed the library using this command `npm install TagCloud --save-dev` and because of a `types` error I imported it like this
`const TagCloud = require('TagCloud');`.  After running the react app multiple spheres appear.

And another problem is when I change the javascript it doesn't affect the sphere, also on every alternate reload it doesn't load

```
import React from 'react';
import './about.scss';

function About() {
  const TagCloud = require('TagCloud');

  const myTags = [
    'JavaScript',
    'CSS',
    'HTML',
    'Vscode',
    'XD',
    'React',
    'Python',
    'Linux',
    'git',
    'Flutter',
    'Dart',
    'Firebase',
    'SASS',
    'JSON',
    'Figma',
  ];

  TagCloud('.content', myTags, {
    radius: 250,
    maxSpeed: 'fast',
    initSpeed: 'fast',
    direction: 135,
    keep: true,
  });

  return (
    <div className="About" id="About">
      <div className="left">
        <div className="heading">
          <h1>ABOUT</h1>
        </div>
        <div className="para">
          <p>
            I am a high school student located in India, I am passionate about
            UI designing, android development, web development and automation.
          </p>
          <br></br>
          <p>
            Love automating daily boring tasks using python, Linux OS, gaming
            and in sports: football and badminton.
          </p>
          <br></br>
          <p>
            <a href="#Contact">Contact me</a>
          </p>
        </div>
      </div>
      <div className="right">
        <span className="content"></span>
      </div>
    </div>
  );
}

export default About;

```

**Comment by JorgeNava** [comment]
Facing same issue, several spheres appear with just one instance of TagCloud.

**Comment by JorgeNava** [comment]
Try removing the   <React.StrictMode> tag in the index.js file from the root path of your react project, that worked for me.

**Comment by Rohith-JN** [comment]
Oh for me this worked:
 
`
const IsTagCloudLoaded = useRef(false)

    useEffect(() => {
        if (IsTagCloudLoaded.current) return

        TagCloud('.content', Tags, {
            radius: 250,
            maxSpeed: 'fast',
            initSpeed: 'fast',
            direction: 135,
            keep: true,
        })

        IsTagCloudLoaded.current = true
    }, []) 
`

**Comment by JorgeNava** [comment]
Great, thanks.
Should we close de Issue? I think it's more an issue with React rather than with the library

**Comment by Rohith-JN** [comment]
Agreed

**Comment by JorgeNava** [comment]
@Rohith-JN could you provide a more detailed code of how you've done it?

**Comment by Rohith-JN** [comment]
I actually got the solution to this problem from stack-overflow, I am not sure how it solved the problem, but if I am not wrong on first render it checks if a TagCloud exists or not. I used it here: [my site](https://rohithnambiar.in)

**Comment by JorgeNava** [comment]
Great, if it was the case that you had the code seriously I'll be very
glad. Btw thats and awesome site, good job.

If it were the case that you had the code seriously, I would really
appreciate it haha
