### ISSUE TITLE
Invert rotation direction / 反转旋转方向

### ISSUE THREAD

**Issue by JCMSimon** [cong-min/TagCloud#33]
🇬🇧
Hey, is there any way that we can have an option to invert the direction it spins depending on the mouse position? currently the items practically run away from you which isnt great for my use case. 

🇨🇳
嘿，我们有没有办法提供一个选项，根据鼠标位置反转旋转方向？
目前，物品几乎都会从你身边跑开，这对我的用例来说不是很好。

**Comment by cong-min** [comment]
LGTM, TagCloud@2.5.0
